### ISSUE TITLE
Docs: link to CHANGELOG file does not exist

### ISSUE THREAD

**Issue by andreysmelter** [vsoch/watchme#29]
The link to CHANGELOG file (https://vsoch.github.io/watchme/changelog/) does not exist (https://vsoch.github.io/watchme/changelog/vsoch/watchme/blob/master/CHANGELOG.md)

This should probably point to: https://github.com/vsoch/watchme/blob/master/CHANGELOG.md

**Comment by vsoch** [comment]
Fixed https://github.com/vsoch/watchme/pull/24/commits/cd8d38a0e51450426fa46558810f1779b2d73560

**Comment by vsoch** [comment]
@andreysmelter if your review is done (or if you want to refresh the code and docs with your changes and continue) then I can merge the PR to do this. Since we've had a change in the install dependencies (adding requests) I'll still wait to release the next version (0.0.15) for when you are done with your review. Let me know your preference! Happy to merge to make it easier to review :)

**Comment by vsoch** [comment]
@andreysmelter I merged the PR (and since I referenced them, it closed all the issues). When you have some time again, this is good news because the fixes should be live! Thanks again for your help to review this.

**Comment by andreysmelter** [comment]
Hi @vsoch I think my review is done.
Those are the issues that I have found and everything else looks excellent!

**Comment by vsoch** [comment]
Sweet!! :D
